erDiagram
    company ||--o{ database_configuration : has
    company {
        UUID id PK
        string domain UK
        string company_name
        date join_date
        string active
        string created_by
        string updated_by
        timestamp created_at
        timestamp updated_at
    }
    database_configuration {
        UUID id PK
        string database_url UK
        string database_username
        string database_password
        string default_schema
        UUID company_id FK
        string created_by
        string updated_by
        timestamp created_at
        timestamp updated_at
    }

